apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: db
  labels:
    app: postgres
data:
  POSTGRES_DATABASE: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  PGDATA: /var/lib/postgresql/data/pgdata