apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: samay1993/node_project
          ports:
            - containerPort: 4000
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 100m
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_HOST
              value: postgres.db
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DATABASE
              value: postgres # default database refer dockerhub
            - name: POSTGRES_PASSWORD
              value: cGFzc3dvcmQ=